### PR TITLE
Check test configuration file path

### PR DESCRIPTION
**Pull request by vadymmarkov**
Fixes an issue with Xcode 7.3.

### CODE REVIEW

**Comment by 3lvis** [comment]
I don't have admin access 💀 

Can you fix that?

**Comment by vadymmarkov** [comment]
@3lvis Thanks 😉

**Comment by 3lvis** [comment]
screen shot 2016-06-23 at 9 13 32 pm

Shipped!

https://github.com/hyperoslo/NSObject-HYPTesting/releases/tag/1.2.1

**Comment by vadymmarkov** [comment]
🚀

**Pull request merged**
